---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    env: apache
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    env: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    env: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      env: apache
  template:
    metadata:
      labels:
        env: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.51
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
