---
apiVersion: v1
kind: Service
metadata:
  name: apache2-svc
  labels:
    env: apache2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    env: apache2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  labels:
    env: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      env: apache2
  template:
    metadata:
      labels:
        env: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:2.4.51
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 2.0
          requests:
            cpu: 1.1
