---
apiVersion: v1
kind: Service
metadata:
  name: aphp-svc
  labels:
    env: aphp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    env: aphp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aphp-deployment
  labels:
    env: aphp
spec:
  replicas: 1
  selector:
    matchLabels:
      env: aphp
  template:
    metadata:
      labels:
        env: aphp
    spec:
      containers:
      - name: aphp
        image: taroball/taro1:php1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
