---
apiVersion: v1
kind: Service
metadata:
  name: taewa2-svc
  labels:
    env: taewa2
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    env: taewa2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taewa2-deployment
  labels:
    env: taewa2
spec:
  replicas: 1
  selector:
    matchLabels:
      env: taewa2
  template:
    metadata:
      labels:
        env: taewa2
    spec:
      containers:
      - name: taewa2
        image: taroball/taro1:smplc3393f8
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1.1
          requests:
            cpu: 1.1
