---
apiVersion: v1
kind: Service
metadata:
  name: taro-svc
  labels:
    env: taro
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    env: taro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taro-deployment
  labels:
    env: taro
spec:
  replicas: 8
  selector:
    matchLabels:
      env: taro
  template:
    metadata:
      labels:
        env: taro
    spec:
      containers:
      - name: taro
        image: taroball/taro1:appd9f52db
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1.0
          requests:
            cpu: 0.71
