---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-15
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-public
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    availabilityZones: ["us-west-2a", "us-west-2b"]
    volumeSize: 20
    # updateConfig:
    #   maxUnavailable: 3 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    labels: {role: worker}
    # Note: unmanaged nodegroups (`nodeGroups` field) use a different structure (map[string]string) to express taints
    taints:
    - key: key1
      value: value1
      effect: NoSchedule
    - key: key2
      effect: NoExecute
    tags:
      nodegroup-role: worker