AWSTemplateFormatVersion: '2010-09-09'

Parameters: 

  myVPC:
    Type: String
  mySubnet1:
    #Description: 
    Type: String
  myInstanceType:
    #Description: Instance Type
    Type: String
    Default: 't3.medium'
  KeyPairName:
    ConstraintDescription: Must be an existing EC2 Keypair.
    #Description: x
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: 'dev-key'
  # AMIimageID:
  #   #Description:
  #   Type: String
  #   Default: ami-123
  LatestAmiId:
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
      Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs'


Resources:

  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref myInstanceType
      IamInstanceProfile: !Sub "${myInstanceProfile}"
      #    Name:  !Ref myInstanceProfile
      KeyName: !Ref KeyPairName
      SubnetId: !Ref mySubnet1
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData: !Base64 
        'Fn::Sub': |-
          #!/bin/bash -xe

          yum update -y
          yum install -y httpd
          service httpd start  
          echo "<html><h1>Hello from JumpHost!</h1></html>" > /var/www/html/test.html

          # cd /tmp
          # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          # unzip awscliv2.zip
          # ./aws/install

          # curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
          # chmod +x kubectl
          # mv /tmp/kubectl /usr/local/bin/

          # curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          # chmod +x /tmp/eksctl && sudo mv /tmp/eksctl /usr/local/bin/

          curl -o /usr/bin/hey https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64
          chmod +x /usr/bin/hey 

          curl -L https://github.com/fortio/fortio/releases/download/v1.19.0/fortio-linux_x64-1.19.0.tgz \
          | sudo tar -C / -xvzpf -

      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-instance"

  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access via port 80
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0


  myInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub '${AWS::StackName}-ec2-instance-profile'
      Path: /
      Roles: 
       - !Ref myInstanceRole

  myInstanceRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore 
      # Policies:
      #   - PolicyName: !Sub ${AWS::StackName}-InlinePolicy
      #     PolicyDocument:
      #       Version: '2012-10-17'
      #       Statement:
      #         -
      #           Effect: Allow
      #           Action: 
      #             - s3:Get*
      #             - s3:List*
      #           Resource: 
      #            - !Sub 'arn:aws:s3:::mybucket'
      #            - !Sub 'arn:aws:s3:::mybucket/*'